# Generated by Django 3.0.5 on 2020-05-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0002_auto_20200421_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantadmin',
            old_name='description',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='restaurantadmin',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurantadmin',
            name='price',
        ),
        migrations.RemoveField(
            model_name='restaurantadmin',
            name='restaurant_name',
        ),
        migrations.RemoveField(
            model_name='restaurantadmin',
            name='school',
        ),
    ]
