# Generated by Django 3.0.5 on 2020-05-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200508_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='picture',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
