# Generated by Django 3.0.5 on 2020-05-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200508_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='picture',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
    ]
