# Generated by Django 3.0.5 on 2020-05-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20200507_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='picture',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
