# Generated by Django 3.0.5 on 2020-05-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20200508_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
