# Generated by Django 3.0.5 on 2020-05-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20200508_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
