# Generated by Django 3.0.5 on 2020-05-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_restaurant_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='x_coord',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='y_coord',
            field=models.FloatField(null=True),
        ),
    ]
