# Generated by Django 3.0.5 on 2020-05-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20200508_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.CharField(default='$', max_length=4),
        ),
    ]
